#!/bin/sh
set -e
. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions
SERVICE_NAME="flexget"
SERVICE_XPATH="/config/services/${SERVICE_NAME}"
case "$1" in
    purge)
        if omv_config_exists ${SERVICE_XPATH}; then
            omv_config_delete ${SERVICE_XPATH}
        fi

        if [ -f "/var/run/${SERVICE_NAME}/${SERVICE_NAME}.pid" ]; then
            PID=$(cat /var/run/${SERVICE_NAME}/${SERVICE_NAME}.pid);
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
            fi
        fi
	
	echo "Removing user ${SERVICE_NAME}"
	userdel -r ${SERVICE_NAME}
	
	echo "Uninstalling ${SERVICE_NAME}:"
	pip uninstall flexget --yes
	
	if [ -d "/home/${SERVICE_NAME}/.${SERVICE_NAME}" ]; then
            echo "Removing /home/${SERVICE_NAME}/.${SERVICE_NAME}"
            rm -rf /home/${SERVICE_NAME}/.${SERVICE_NAME}	
	fi
	
	if [ -f "/etc/init.d/${SERVICE_NAME}" ]; then
	    echo "Removing /etc/init.d/${SERVICE_NAME}"
	    rm /etc/init.d/${SERVICE_NAME}
	fi

        if [ -f "/etc/default/${SERVICE_NAME}" ]; then
	    echo "Removing /etc/default/${SERVICE_NAME}"
	    rm /etc/default/${SERVICE_NAME}
	fi

    ;;
    remove)
    ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
#DEBHELPER#
exit 0
